- name: EC2
  hosts: publicec2
  become: true
  tasks:
  - name: Ensure boto and boto3 modules are installed
    pip:
      name: "{{ item }}"
    with_items:
      - boto3
      - botocore
    delegate_to: 54.161.27.169

  - name: create ec2
    amazon.aws.ec2_instance:
      aws_access_key: "{{ AWS_ACCESS_KEY }}"
      aws_secret_key: "{{ AWS_SECRET_KEY }}"
      name: public_ec2
      key_name: mykey
      region: us-east-1
      instance_type: t2.micro
      image_id: ami-053b0d53c279acc90
      vpc_subnet_id: subnet-046affe74a77ebb88
      security_group: sg-00822c59eae4710c7
      exact_count: 1
    register: ec2_instance

  - ansible.builtin.pause:
      seconds: 30

  - name: Add the private EC2 instance to the host group
    template:
        src: temp.j2
        dest: inventory.yml
    become: yes
