- name: EC2
  hosts: publicec2
  become: true
  tasks:
  # - name: Ensure boto and boto3 modules are installed
  #   pip:
  #     name: "{{ item }}"
  #   with_items:
  #     - boto3
  #     - botocore
  #   delegate_to:
  
- name: Include a play after another play
  ansible.builtin.import_playbook: play2.yml
  
  - name: create ec2
    amazon.aws.ec2_instance:
      aws_access_key: "{{ AWS_ACCESS_KEY }}"
      aws_secret_key: "{{ AWS_SECRET_KEY }}"
      name: private_ec2
      key_name: mykey
      region: us-east-1
      instance_type: t2.micro
      image_id: ami-053b0d53c279acc90
      vpc_subnet_id: subnet-02a90fdef55037b81
      security_group: sg-0101d7d5488c2fc4f
      exact_count: 1
    register: ec2_instance

  - ansible.builtin.pause:
      seconds: 15

  - name: Add the private EC2 instance to the host group
    template:
        src: temp.j2
        dest: /etc/ansible/hosts
    become: yes

  - name: play 2nd book
    ansible.builtin.command: ansible-playbook play2.yml
