version: 2
jobs:
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9d:25:8d:0a:23:c7:18:61:8a:1c:b5:e3:60:04:6d:87"
  build:
    docker:
      - image: aseelibrahimm/docker-ansible-awscli:lts
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run Ansible playbook
          command: |
            ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/aws ubuntu@ec2-54-234-96-26.compute-1.amazonaws.com "
            ansible-playbook -i inventory.yml --private-key=$HOME/.ssh/aws --extra-vars "AWS_ACCESS_KEY=$AWS_ACCESS_KEY_ID AWS_SECRET_KEY=$AWS_SECRET_ACCESS_KEY" servers.yml"
            
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
